function am()
Ts=0.01;
t=0:Ts:10;%时间
w=10;
mp=4*sin(w.*t+7);%调制信号
w0=50.*w;
c=cos(w0.*t);%载波

%调制信号
%时域
subplot(2,4,1);
plot(t,mp);
title('调制前时域特性');
xlabel('Time');
ylabel('Amplitude');
%频域
MP=fft(mp);
MP=fftshift(MP);
fs=1/Ts;
f=(-length(MP)/2:length(MP)/2-1)*fs/length(MP);
subplot(2,4,5);
plot(f,abs(MP));
title('调制前频域特性');
xlabel('Frequency');
ylabel('Manitude');

%调制
m=mp+abs(min(mp));
s=c.*m;%已调信号
%时域
subplot(2,4,2);
plot(t,s);
title('调制后时域特性');
xlabel('Time');
ylabel('Amplitude');
%频域
S=fft(s);
S=fftshift(S);
subplot(2,4,6);
plot(f,abs(S));
title('调制后频域特性');
xlabel('Frequency');
ylabel('Manitude');

%相干解调
z=s.*c;
%低通滤波器
z=lowpass(z,w/2/pi,fs);
sp=2.*z-abs(min(mp));
%时域
subplot(2,4,3);
plot(t,sp);
title('解调后时域特性');
xlabel('Time');
ylabel('Amplitude');
%频域
SP=fft(sp);
SP=fftshift(SP);
subplot(2,4,7);
plot(f,abs(SP));
title('解调后频域特性');
xlabel('Frequency');
ylabel('Manitude');

%载波
%时域
subplot(2,4,4);
plot(t,c);
title('载波时域特性');
xlabel('Time');
ylabel('Amplitude');
%频域
C=fft(c);
C=fftshift(C);
subplot(2,4,8);
plot(f,abs(C));
title('载波频域特性');
xlabel('Frequency');
ylabel('Manitude');
